Traceback (most recent call last):
  File "1.py", line 1, in <module>
    raise NameError("return !")
NameError: return !
